name: Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest]
        python-version: ["3.8"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Packages from requirements.txt
        run: pip install -r weights_export/requirements.txt

      - name: Saving Model Weights
        run: python weights_export/export_model_weights.py

      - name: Create Build Environment
        run: mkdir build

      - name: Configure CMake
        working-directory: ./build
        run: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DGGML_TEST_COVERAGE=ON -DGGML_CLBLAST=ON ..

      - name: Build
        working-directory: ./build
        run: make

      - name: Test
        working-directory: ./build
        run: ./example/main